package com.agentcraft.terminal.omo;

import com.agentcraft.terminal.TerminalMod;
import net.fabricmc.fabric.api.client.rendering.v1.hud.HudElement;
import net.minecraft.client.MinecraftClient;
import net.minecraft.client.gl.RenderPipelines;
import net.minecraft.client.gui.DrawContext;
import net.minecraft.client.render.RenderTickCounter;
import net.minecraft.client.texture.NativeImage;
import net.minecraft.client.texture.NativeImageBackedTexture;
import net.minecraft.util.Identifier;

import java.io.InputStream;

/**
 * The Omo persistent overlay — a 160px floating "holoscope" of Omo's head
 * tucked into the top-left of the Minecraft window.
 *
 * The holoscope chrome (soft cyan radial glow under the head, circular
 * alpha mask, thin holo ring) is BAKED into the PNG by the browser
 * overlay page's 2D compositor. That means this layer's job is delightfully
 * boring: blit the latest live frame at 1:1 pixel size with an optional
 * per-mode alpha pulse for breathing intensity. See
 * {@code face/public/overlay-app.js::composite} for the chrome math.
 *
 * Two render paths, picked per frame:
 *   1. LIVE — if {@link OmoFramePoller} has a fresh PNG frame (browser
 *      overlay tab open at localhost:8080/overlay), upload it to a
 *      dynamic GPU texture and blit.
 *   2. PLACEHOLDER — when the live capture is unavailable, draw a tiny
 *      programmatic "Omo is loading" disc with two eye dots + a hint
 *      string. NO procedural sprite frames — those were placeholders and
 *      looked amateur next to the live render.
 *
 * The live texture is re-uploaded ONLY when a new frame ID arrives from
 * the poller — uploading every render tick would crater FPS. The dynamic
 * texture is registered under {@code agentcraft-terminal:omo/live}.
 */
public class OmoHudLayer implements HudElement {

    // Display size — must match FRAME_PX in face/public/overlay-app.js so
    // we never resample. 256 with 2× WebGL supersampling on the capture
    // side yields crisp holo materials in the corner without flooding it.
    private static final int SPRITE_PX = 256;

    // Offset from the top-left corner. 10/10 lands the holoscope a touch
    // inside the screen edge — visually inset, not flush, per the user's
    // "fit exactly inside the top-left corner" framing.
    private static final int MARGIN_X = 10;
    private static final int MARGIN_Y = 10;

    // Identifier the dynamic live-frame texture is registered under.
    private static final Identifier LIVE_TEX_ID =
        Identifier.of(TerminalMod.MOD_ID, "omo/live");
    // Identifier for the bundled static fallback PNG (a one-shot baked
    // render of avatar.js at the same camera framing as the live overlay).
    // Shown when the live frame stream is briefly unavailable.
    private static final Identifier STATIC_TEX_ID =
        Identifier.of(TerminalMod.MOD_ID, "omo/static");
    // Path inside the mod jar where the baked PNG lives. Generated by
    // face/scripts/bake-static-face.js.
    private static final String STATIC_RESOURCE_PATH =
        "/assets/" + TerminalMod.MOD_ID + "/textures/omo/omo_static.png";

    private final OmoStatePoller statePoller;
    private final OmoFramePoller framePoller;

    // Live-frame texture state. We hold one NativeImageBackedTexture for
    // the lifetime of the mod and replace its inner image whenever a new
    // frame arrives. `uploadedFrameId` tracks which poller frame is
    // currently on the GPU so we don't re-upload on every render call.
    private NativeImageBackedTexture liveTex;
    private long uploadedFrameId = -1L;
    private boolean liveTexRegistered = false;
    private int liveW = SPRITE_PX;
    private int liveH = SPRITE_PX;

    // Static-fallback texture state. Loaded lazily on first need from the
    // mod jar; if the PNG is missing or fails to decode we set `staticFailed`
    // so we don't keep retrying every tick.
    private NativeImageBackedTexture staticTex;
    private boolean staticTexRegistered = false;
    private boolean staticFailed = false;
    private int staticW = SPRITE_PX;
    private int staticH = SPRITE_PX;

    public OmoHudLayer(OmoStatePoller statePoller, OmoFramePoller framePoller) {
        this.statePoller = statePoller;
        this.framePoller = framePoller;
    }

    @Override
    public void render(DrawContext ctx, RenderTickCounter tickCounter) {
        // Try the live path first. Falls through to the placeholder on
        // any failure (overlay tab not open, runtime down, decode error).
        if (!tryRenderLive(ctx)) {
            renderPlaceholder(ctx);
        }
        // Per-mode cue painted ON TOP of either path so the user always
        // knows whether Omo is currently hearing them (V keybind toggled
        // voice on, browser tab is recording), thinking (tool dispatch),
        // or speaking (model audio playing back). The cue is independent
        // of the live-frame rendering pipeline above — it's a couple of
        // ctx.fill rectangles tacked under the holoscope so the existing
        // texture upload / sizing / alpha-pulse code stays untouched.
        renderModeCue(ctx);
    }

    /**
     * Per-mode breathing pulse for the live blit's alpha channel. The
     * heavy chrome animation already lives in the JS compositor; this is
     * just a multiplicative shimmer so the in-game blit still feels
     * "alive" between PNG arrivals (which only update at ~12 Hz).
     *
     * @return alpha byte (0..255), packed into the ARGB tint passed to
     *         drawTexture(..., color).
     */
    private int liveAlpha() {
        OmoFaceState state = statePoller.get();
        long t = System.currentTimeMillis();
        // Hz of the shimmer per mode. Idle is glacial; speaking is brisk.
        double freq;
        double base;
        double amp;
        switch (state) {
            case LISTENING:   freq = 0.9;  base = 0.96; amp = 0.04; break;
            case SPEAKING:    freq = 1.8;  base = 0.97; amp = 0.03; break;
            case CELEBRATING: freq = 2.4;  base = 1.00; amp = 0.00; break; // flat at peak
            case THINKING:    freq = 0.6;  base = 0.92; amp = 0.06; break;
            case IDLE:
            default:          freq = 0.5;  base = 0.97; amp = 0.03; break;
        }
        double sec = t / 1000.0;
        double a = base + Math.sin(sec * freq * Math.PI * 2.0) * amp;
        if (a < 0.7) a = 0.7;
        if (a > 1.0) a = 1.0;
        return (int) Math.round(a * 255.0);
    }

    /** @return true if a live frame was successfully drawn this tick. */
    private boolean tryRenderLive(DrawContext ctx) {
        NativeImage img = framePoller.current();
        if (img == null) return false;

        long fid = framePoller.currentFrameId();
        if (fid != uploadedFrameId) {
            try {
                int w = img.getWidth();
                int h = img.getHeight();
                if (liveTex == null || liveW != w || liveH != h
                    || liveTex.getImage() == null
                    || liveTex.getImage().getWidth() != w
                    || liveTex.getImage().getHeight() != h) {
                    // First frame, or the source dimensions changed —
                    // rebuild the texture. Dispose the previous one first
                    // so we don't leak native memory.
                    if (liveTex != null) {
                        try { liveTex.close(); } catch (Throwable ignored) {}
                    }
                    NativeImage owned = new NativeImage(w, h, false);
                    owned.copyFrom(img);
                    liveTex = new NativeImageBackedTexture(() -> "omo-live", owned);
                    liveW = w;
                    liveH = h;
                    liveTexRegistered = false;
                } else {
                    // Same dimensions — just memcpy pixels into the existing
                    // NativeImage and re-upload.
                    liveTex.getImage().copyFrom(img);
                }
                liveTex.upload();
                if (!liveTexRegistered) {
                    MinecraftClient mc = MinecraftClient.getInstance();
                    if (mc != null && mc.getTextureManager() != null) {
                        mc.getTextureManager().registerTexture(LIVE_TEX_ID, liveTex);
                        liveTexRegistered = true;
                    }
                }
                uploadedFrameId = fid;
            } catch (Throwable t) {
                // If upload fails for any reason, drop to the placeholder
                // this tick — we'll try again next frame.
                return false;
            }
        }
        if (!liveTexRegistered) return false;

        int x = MARGIN_X;
        int y = MARGIN_Y;
        // 11-arg drawTexture: pipeline, id, x, y, u, v, w, h, texW, texH, color.
        // Color tint = (alpha << 24) | 0x00FFFFFF — modulates only alpha
        // for the breathing pulse, leaves RGB untouched. We render at
        // SPRITE_PX so the blit is 1:1 with the source PNG when SPRITE_PX
        // == liveW (the normal case); if the dimensions ever mismatch,
        // texW/texH still describes the source so the sampling stays sane.
        int tint = (liveAlpha() << 24) | 0x00FFFFFF;
        ctx.drawTexture(
            RenderPipelines.GUI_TEXTURED,
            LIVE_TEX_ID,
            x, y,
            0f, 0f,
            SPRITE_PX, SPRITE_PX,
            liveW, liveH,
            tint
        );
        return true;
    }

    /**
     * Fallback shown when the live capture is unavailable. Blits a bundled
     * static PNG of the real avatar.js render (baked once via
     * face/scripts/bake-static-face.js) so the user can't tell the
     * difference for short outages — the static image is the exact same
     * camera framing + chrome compositor as a live frame.
     *
     * Loads lazily on first call. If the bundled PNG is missing or fails
     * to decode for any reason we silently draw nothing — Omo just briefly
     * disappears instead of falling back to the old programmatic placeholder
     * (which the user called "amateur"). The live stream usually warms up
     * within a second of face boot so this gap is invisible in practice.
     */
    private void renderPlaceholder(DrawContext ctx) {
        if (!ensureStaticTexture()) return;
        int x = MARGIN_X;
        int y = MARGIN_Y;
        int tint = (liveAlpha() << 24) | 0x00FFFFFF;
        ctx.drawTexture(
            RenderPipelines.GUI_TEXTURED,
            STATIC_TEX_ID,
            x, y,
            0f, 0f,
            SPRITE_PX, SPRITE_PX,
            staticW, staticH,
            tint
        );
    }

    /**
     * Load the bundled static-fallback PNG from the mod jar on first
     * demand. Returns true once the texture is registered and ready to
     * blit. After a permanent failure (missing resource, decode error)
     * we latch {@code staticFailed} so we don't retry every render tick.
     */
    private boolean ensureStaticTexture() {
        if (staticTexRegistered) return true;
        if (staticFailed) return false;
        InputStream in = OmoHudLayer.class.getResourceAsStream(STATIC_RESOURCE_PATH);
        if (in == null) {
            staticFailed = true;
            System.out.println("[omo-overlay] static fallback PNG missing at " + STATIC_RESOURCE_PATH
                + " — run `npm run bake-static-face` in face/");
            return false;
        }
        try (InputStream stream = in) {
            NativeImage img = NativeImage.read(stream);
            staticW = img.getWidth();
            staticH = img.getHeight();
            staticTex = new NativeImageBackedTexture(() -> "omo-static", img);
            staticTex.upload();
            MinecraftClient mc = MinecraftClient.getInstance();
            if (mc == null || mc.getTextureManager() == null) {
                // Texture manager not ready yet — try again next tick. Don't
                // latch the failure flag.
                try { staticTex.close(); } catch (Throwable ignored) {}
                staticTex = null;
                return false;
            }
            mc.getTextureManager().registerTexture(STATIC_TEX_ID, staticTex);
            staticTexRegistered = true;
            return true;
        } catch (Throwable t) {
            staticFailed = true;
            System.out.println("[omo-overlay] static fallback PNG load failed: "
                + t.getClass().getSimpleName()
                + (t.getMessage() != null ? " " + t.getMessage() : ""));
            return false;
        }
    }

    /**
     * Paint a small per-mode cue under the holoscope so the user can tell
     * at a glance what Omo is doing. Three meaningfully-different states:
     * <ul>
     *   <li>LISTENING — pulsing pink mic glyph + "listening" label.
     *       Tells the user Omo is hearing them right now (V keybind on).</li>
     *   <li>THINKING — three bouncing cyan dots + "thinking" label.</li>
     *   <li>SPEAKING — three vertical cyan bars (faux waveform) +
     *       "speaking" label.</li>
     * </ul>
     * Drawn entirely with {@link DrawContext#fill} — no PNG assets. Sits
     * a few pixels below the holoscope so it never overlaps the head.
     */
    private void renderModeCue(DrawContext ctx) {
        OmoFaceState state = statePoller.get();
        // IDLE / CELEBRATING use the existing alpha-pulse on the holoscope
        // itself; no need for an extra cue below it.
        if (state == OmoFaceState.IDLE || state == OmoFaceState.CELEBRATING) return;

        int cueY = MARGIN_Y + SPRITE_PX + 4;
        int cueH = 16;
        int cueX = MARGIN_X;
        int cueW = SPRITE_PX;
        int cx = cueX + cueW / 2;
        int cy = cueY + cueH / 2;
        long t = System.currentTimeMillis();

        // Pill background — same in every state, mode-tinted alpha.
        switch (state) {
            case LISTENING: {
                // Pulsing pink halo background.
                double sec = t / 1000.0;
                double pulse = 0.55 + 0.35 * (Math.sin(sec * Math.PI * 2.0 * 1.3) * 0.5 + 0.5);
                int bgAlpha = (int) Math.round(pulse * 180);
                int bg = (bgAlpha << 24) | 0xFF66B3; // pink (#FF66B3)
                ctx.fill(cueX, cueY, cueX + cueW, cueY + cueH, bg);
                // Soft pink edge highlight (top/bottom 1px).
                int edge = 0xCCFF99CC;
                ctx.fill(cueX, cueY, cueX + cueW, cueY + 1, edge);
                ctx.fill(cueX, cueY + cueH - 1, cueX + cueW, cueY + cueH, edge);

                // Mic glyph — a rounded capsule (the head) + a stand bar +
                // a base. Three fills total. Positioned left of the label.
                int gx = cueX + 8;
                int micHeadW = 4;
                int micHeadH = 6;
                int micColor = 0xFFFFFFFF;
                // head
                ctx.fill(gx, cy - micHeadH / 2 - 1, gx + micHeadW, cy + micHeadH / 2 - 1, micColor);
                // stand
                ctx.fill(gx + 1, cy + micHeadH / 2 - 1, gx + micHeadW - 1, cy + micHeadH / 2 + 1, micColor);
                // base
                ctx.fill(gx - 1, cy + micHeadH / 2 + 1, gx + micHeadW + 1, cy + micHeadH / 2 + 2, micColor);

                drawCueLabel(ctx, "listening", cueX, cueY, cueW, cueH, 0xFFFFFFFF);
                break;
            }
            case THINKING: {
                // Soft cyan background + three bouncing dots.
                int bg = 0x99005577;
                ctx.fill(cueX, cueY, cueX + cueW, cueY + cueH, bg);
                int edge = 0xCC66E7FF;
                ctx.fill(cueX, cueY, cueX + cueW, cueY + 1, edge);
                ctx.fill(cueX, cueY + cueH - 1, cueX + cueW, cueY + cueH, edge);

                int dotR = 2;
                int gap  = 6;
                int totalW = dotR * 6 + gap * 2;
                int dx0 = cueX + 8;
                for (int i = 0; i < 3; i++) {
                    double phase = (t / 250.0) - i * 0.5;
                    double bob = Math.sin(phase) * 2.0;
                    int dxc = dx0 + i * (dotR * 2 + gap);
                    int dyc = cy + (int) Math.round(bob);
                    ctx.fill(dxc - dotR, dyc - dotR, dxc + dotR, dyc + dotR, 0xFFFFFFFF);
                }
                drawCueLabel(ctx, "thinking", cueX, cueY, cueW, cueH, 0xFFE6F8FF);
                break;
            }
            case SPEAKING: {
                // Cyan background + three vertical waveform bars whose
                // heights breathe out of phase.
                int bg = 0xAA003C66;
                ctx.fill(cueX, cueY, cueX + cueW, cueY + cueH, bg);
                int edge = 0xDD66E7FF;
                ctx.fill(cueX, cueY, cueX + cueW, cueY + 1, edge);
                ctx.fill(cueX, cueY + cueH - 1, cueX + cueW, cueY + cueH, edge);

                int barW = 2;
                int barGap = 2;
                int barsX = cueX + 8;
                for (int i = 0; i < 4; i++) {
                    double phase = (t / 110.0) - i * 0.9;
                    double mag = (Math.sin(phase) * 0.5 + 0.5);
                    int h = (int) Math.round(3 + mag * 9);
                    int bx0 = barsX + i * (barW + barGap);
                    int by0 = cy - h / 2;
                    ctx.fill(bx0, by0, bx0 + barW, by0 + h, 0xFFFFFFFF);
                }
                drawCueLabel(ctx, "speaking", cueX, cueY, cueW, cueH, 0xFFE6F8FF);
                break;
            }
            default:
                // Unreachable — IDLE/CELEBRATING short-circuited above.
        }
    }

    private void drawCueLabel(DrawContext ctx, String label, int cueX, int cueY, int cueW, int cueH, int color) {
        MinecraftClient mc = MinecraftClient.getInstance();
        if (mc == null || mc.textRenderer == null) return;
        int tw = mc.textRenderer.getWidth(label);
        // Right-align the label inside the pill, leaving the left side
        // for the per-mode glyph. 6px right padding feels balanced.
        int tx = cueX + cueW - tw - 6;
        int ty = cueY + (cueH - mc.textRenderer.fontHeight) / 2 + 1;
        ctx.drawTextWithShadow(mc.textRenderer, label, tx, ty, color);
    }
}
